### ISSUE TITLE
Bump dry-configurable version dependency to avoid conflict with latest dry-validation

### ISSUE THREAD

**Issue by TheFifthFreedom** [rubygarage/api_struct#9]
@kirillshevch @bezrukavyi @andy1341 thanks again for your great work on this library 🙏I noticed that when including `api_struct` 1.0.3 alongside the new `dry-validation` gem that recently reached 1.0.0, a conflict occurs over `dry-configurable`:
```
Bundler could not find compatible versions for gem "dry-configurable":
  In snapshot (Gemfile.lock):
    dry-configurable (= 0.7.0)

  In Gemfile:
    api_struct (~> 1.0.3) was resolved to 1.0.3, which depends on
      dry-configurable (~> 0.7.0)

    dry-validation (~> 1.2.1) was resolved to 1.2.1, which depends on
      dry-schema (~> 1.0, >= 1.3.1) was resolved to 1.3.1, which depends on
        dry-configurable (~> 0.8, >= 0.8.3)
```
Any chance you could bump up the `dry-configurable` dependency version of `api_struct` so both gems could be used simultaneously? Otherwise we'd be forced to bump down `dry-validation` to 0.13.0, and thus not be able to take advantage of the new DSL, validation logic, `dry-schema` gem etc. that come with version 1.0.0+

**Comment by kirillshevch** [comment]
Hi @TheFifthFreedom! Thank you for request. 
We will try to remove hardcoded versions, I think it shouldn't break anything.

**Comment by kirillshevch** [comment]
I fixed this here: https://github.com/rubygarage/api_struct/pull/10

**Comment by kirillshevch** [comment]
Released https://rubygems.org/gems/api_struct/versions/1.0.4
Let me know if it works for you

**Comment by TheFifthFreedom** [comment]
It works! Thank you so much for the swift reply @kirillshevch - gonna close this issue 👌

**Comment by flvrone** [comment]
Hey, @kirillshevch, something breaks for me when I update to version newer than `1.0.3`, and there are no Changelog updates so I don't even know what's inside :)

Anyway, I'm just reporting that something is wrong on my side, I will give you more info on this topic when having enough time to investigate and figure out why was that.
